import { useState } from 'react';

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import axios from 'axios';

import { UiFileInputButton } from '../components/UiFileInputButton';

export default function Home() {
  const [pdf, setPdf] = useState('')
  const onChange = async (formData) => {
    const config = {
      headers: { 'content-type': 'multipart/form-data' },
      onUploadProgress: (event) => {
        console.log(`Current progress:`, Math.round((event.loaded * 100) / event.total));
      },
    };

    const { data } = await axios.post('/api/uploads', formData, config);

    const response2 = await axios.post('/api/pdfparser', { fileName: data.fileName });
    console.log('json data', response2.data);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Loan Calculator!
        </h1>

        <p className={styles.description}>
          Get started by uploading your bank statement
        </p>

        <UiFileInputButton
          label="Upload Single File"
          uploadFileName="theFiles"
          onChange={onChange}
        />
      </main>
      <footer className={styles.footer}>
        <h4>Powered by Niema</h4>
      </footer>
    </div>
  )
}
